
spring:
  application:
    name: KafkaTest
  kafka:
    producer:
      bootstrap-servers: 47.95.202.**:19092
      retries: 0
      acks: 1
      batch-size: 16384 #16K
      buffer-memory: 33554432 #32M
      properties:
        linger.ms: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: 47.95.202.**:19092
      group-id: CID-iotToExhaust
      enable-auto-commit: true
      auto-commit-interval: 1000
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 30000 #consumer\u5065\u5EB7\u68C0\u67E5\u5FC3\u8DF3\uFF0C\u9ED8\u8BA410s
        max.poll.interval.ms: 300000 #\u83B7\u53D6\u6D88\u606F\u540E\u63D0\u4EA4\u504F\u79FB\u91CF\u7684\u65F6\u95F4\u9650\u5236\uFF0C\u9ED8\u8BA4\u4E5F\u662F5min
    listener:
      #\u6307\u5B9A\u7279\u6B8A\u7684\u6D88\u8D39\u6A21\u5F0F\uFF0C\u4E00\u822C\u7684\u81EA\u52A8\u63D0\u4EA4\u504F\u79FB\u91CF\u4E0D\u9700\u8981\u914D\u7F6E
      #RECORD :\u5F53listener\u4E00\u8BFB\u5230\u6D88\u606F\uFF0C\u5C31\u63D0\u4EA4offset
      #BATCH: poll() \u51FD\u6570\u8BFB\u53D6\u5230\u7684\u6240\u6709\u6D88\u606F,\u5C31\u63D0\u4EA4offset
      #TIME: \u5F53\u8D85\u8FC7\u8BBE\u7F6E\u7684ackTime \uFF0C\u5373\u63D0\u4EA4Offset
      #COUNT \uFF1A\u5F53\u8D85\u8FC7\u8BBE\u7F6E\u7684COUNT\uFF0C\u5373\u63D0\u4EA4Offset
      #COUNT_TIME \uFF1ATIME\u548CCOUNT\u4E24\u4E2A\u6761\u4EF6\u90FD\u6EE1\u8DB3\uFF0C\u63D0\u4EA4offset
      #MANUAL \uFF1A Acknowledgment.acknowledge()\u63D0\u4EA4Offset\uFF0C\u548CBatch\u7C7B\u4F3C
      #MANUAL_IMMEDIATE\uFF1A Acknowledgment.acknowledge()\u88AB\u8C03\u7528\u5373\u63D0\u4EA4Offset
      ack-mode: record
